version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4 #assignment for module 4.5
  heroku: circleci/heroku@2.0.0 #lesson work for module 4.6
  
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

#start of assignment for module 4.5
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: tshhh123/container-assignment-4.5
          tag: <<pipeline.git.tag>> #lesson work for module 4.6
          # tag: "latestassignment" #assignment for module 4.5
      - docker/push:
          image: tshhh123/container-assignment-4.5
          tag: <<pipeline.git.tag>> #lesson work for module 4.6
          # tag: "latestassignment" #assignment for module 4.5
#end of assignment for module 4.5

#start of lesson work for module 4.6
  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - checkout
  #     - heroku/install
  #     - run:
  #         name: Heroku Container Push
  #         command: |
  #           heroku container:login
  #           heroku container:push web -a tshhh123-devops
  #           heroku container:release web -a tshhh123-devops  

  pull-and-deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - docker/pull:
          images: tshhh123/container-assignment-4.5:<<pipeline.git.tag>>
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            docker tag tshhh123/container-assignment-4.5:<<pipeline.git.tag>> registry.heroku.com/tshhh123-devops/web
            docker push registry.heroku.com/tshhh123-devops/web
            heroku container:release web -a tshhh123-devops  
#end of lesson work for module 4.6

workflows:
  simple_workflow:
    jobs:
      - build:
          filters: #assignment for module 4.6
            branches:
              only: main
      - test:
          requires:
            - build
          filters: #assignment for module 4.6
            branches:
              only: main
      - build-and-push: #start of assignment for module 4.5
          requires:
            - test #end of assignment for module 4.5
          filters: #assignment for module 4.6
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/
      # - deploy:  #start of lesson work for module 4.6
      #     requires:
      #       - build-and-push
      - pull-and-deploy: 
          requires:
            - build-and-push  #end of lesson work for module 4.6
          filters: #assignment for module 4.6
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/