version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  # publish:
  #     # Assignment
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: npm
  #     - run: |
  #         echo "Running docker..."
  #         docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:firsttest
  #         ddocker push
  # build-and-push:
  #   executor: docker/docker
  #   steps:
  #     - setup_remote_docker
  #     - checkout
  #     - docker/check
  #     - docker/build:
  #         image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
  #     - docker/push:
  #         image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      # - run:
      #     command: |
      #       echo "Digest is: $(</tmp/digest.txt)"

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: tshhh123/container-assignment-4.5
          auth:
            username: $DOCKER_USER
            password: $DOCKER_PASS
          tag: "testassignment"
      - docker/push:
          image: tshhh123/container-assignment-4.5
          tag: "testassignment"
          # tag: testassignment
          # docker login -u $DOCKER_USER -p $DOCKER_PASS <- put under run command
      # - run:
      #     name: Docker Login
      #     command: |
      #       TAG=testassignment
      #       docker build -t tshhh123/container-assignment-4.5:$TAG .
      #       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #       docker push container-assignment-4.5/container-assignment-4.5:$TAG

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
  # assignmenttest:
  #   jobs:
  #     - build-and-push
  #         requires:
  #           - test