version: 2.1

orbs:
  node: circleci/node@5.0.1
  
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  optional_publish:
      # Assignment
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running docker..."
          docker build -t tshhh123/container-assignment-4.5:firsttest
          ddocker push

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
